services:
  frontend:
    build: 
      context: .
      target: runtime
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    